name: Build and Deploy for daejangjung2 server to AWS EC2 (CI/CD)

on:
  pull_request:
    branches:
      - develop
    types: [closed]

env:
  PROJECT_NAME: daejangjung2_server
  BUCKET_NAME: daejangjung2-s3-bucket
  CODE_DEPLOY_APP_NAME: daejangjung2
  DEPLOYMENT_GROUP_NAME: daejangjung2-deployment-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: touch ./greatjourney/src/main/resources/application.properties
    - run: echo "${{ secrets.APPLICATION }}" > ./greatjourney/src/main/resources/application.properties
    - run: cat ./greatjourney/src/main/resources/application.properties
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: List current directory
      run: ls -al

    - name: List greatjourney directory
      run: ls -al ./greatjourney
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./greatjourney/gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
      working-directory: ./greatjourney

    # 압축 파일 만들기
    - name: Make Zip File
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash
      
    # AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    # S3 버킷으로 파일을 업로드
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

    # S3 버킷에 업로드 된 파일을 대상으로 CodeDeploy에서 배포 요청
    - name: Code Deploy
      run: |
        aws deploy create-deployment \
        --application-name $CODE_DEPLOY_APP_NAME \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name $DEPLOYMENT_GROUP_NAME \
        --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
